### ISSUE TITLE
Odkaz v [source] v popisu funkce nefunguje

### ISSUE THREAD

**Issue by Glutexo** [nait-aul/doksit#21]
V adrese odkazující na GitHub je v názvu projektu koncovka .git navíc. Nemá tam být.

zdravi @encukou

**Comment by nait-aul** [comment]
@Glutexo Tak dalsi opravny commit uz je snad OK za prepokladu, ze nikdo nepouzije vetev `.git/blob/`, bo to bych se uz divil, co to davaj lidi za pojmenovani + pridano osetreni jen na prvni vyskyt tohoto patternu.

**Comment by nait-aul** [comment]
@Glutexo Tak jsem se nad tim poradne zamyslel (hezky v klidu) a napsal jsem uplne debilne. Spravne ted muze frajer / frajerka i nazev vetve `.git/blob/`, je mi to sumak.

Brzy to sem mergnu, ted akorat to predelavam do OOP vcetne abstraktnich trid pro budouci 3rd party parsery aj, proste at to je skalovatelnejsi do budoucna (hlavne pro nove supr featury, ktery me napadly po pyvku). Na to by byl mix proceduralni pristupu a lehce funkcionalni hodne kratky :smile: (ano, chyba v navrhu, ale na zacatku jsem to necekal, ze bych to nekam vobrovsky dotahnul)

**Comment by Glutexo** [comment]
Bezva bezva! :) Rád se mkrnu, až to tu bude.

Jinak větev obsahující `/blob/` v Gitu existovat zřejmě nemůže. (`fatal: 'aaa.git/blob/' is not a valid branch name`) Ale končící na `.git` úplně v klidu. Zaprudil jsem si s tím hlavně proto, že je docela unavující, jaká spousta knihoven předpokládá, že někde něco nebude. A pak vznikají záhadné chyby když máš někde mezeru, neASCII písmeno, znak který se musí escapovat a tak podobně. Navíc často i v případech, které rozhodně nespadají do kategorie: „Chci si znepříjemnit život.“ :D

**Comment by nait-aul** [comment]
Jasny kapisto. Tak ja jsem hlavne rad, ze se na tuhle chybku prislo. Zejmena z toho duvodu, abych se poradne neztrapnil na Pyconu, ze si to muzou naklonovat a ejhle, vono to nejde jak rikas ...
